"""initial_schema

Revision ID: 801b027d587a
Revises: 
Create Date: 2026-05-02 14:38:22.498357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801b027d587a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('training_rows', sa.Integer(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_tag')
    )
    op.create_table('transactions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('merchant_category', sa.String(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_fingerprint', sa.String(), nullable=True),
    sa.Column('raw_features', sa.JSON(), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('is_fraud_predicted', sa.Boolean(), nullable=True),
    sa.Column('is_fraud_actual', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('model_version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('true_positive_rate', sa.Float(), nullable=True),
    sa.Column('dataset_label', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_snapshots',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('model_version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('psi_score', sa.Float(), nullable=True),
    sa.Column('mean_train', sa.Float(), nullable=True),
    sa.Column('mean_recent', sa.Float(), nullable=True),
    sa.Column('drift_flagged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drift_snapshots_model_version_id', 'drift_snapshots', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_drift_snapshots_snapshot_date'), 'drift_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drift_snapshots_snapshot_date'), table_name='drift_snapshots')
    op.drop_index('ix_drift_snapshots_model_version_id', table_name='drift_snapshots')
    op.drop_table('drift_snapshots')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
